### Data Transformation Parameters
data_transforms:
  train_params: ['default', 'noise', 'pitch', 'pitch_noise']
  test_params: ['default']

### Model Parameters
model_params:
  CNN:
    n_filters: 256
    kernel_size: 5
    pool_size: 2
    dropout_rate: 0.32
