### ================================================================
###                 MODEL SERVING CONFIGURATION
### ================================================================

model_deploy:
  model_name: model-name
  machine_type: "n1-standard-4"
  min_replica_count: 1
  max_replica_count: 1
  traffic_percentage: 100
  scaler_path: /gcs/artifacts-speech-emotion/data_transformation/std_scaler.bin
