artifacts_root: src/mlcore/artifacts

### ================================================================
###                 DATA GEN CONFIGURATION
### ================================================================
data_generation:
  gcp_metadata_bucket: metadata_store_bucket
  gcp_train_bucket: train-bucket-model
  gcp_test_bucket: test-bucket-model
  metadata_dir: './metadata'
  train_dir: './train'
  test_dir: './test'
