### ================================================================
###             MODEL EVALUATION CONFIGURATION
### ================================================================

model_server:
  scaler_path: /gcs/data_transformation/std_scaler.bin
  encoder_path: /gcs/model_training/encoder.bin
  